### ISSUE TITLE
Balinese vowel signs overlap U+1B1B

### ISSUE THREAD

**Issue by dscorbett** [notofonts/balinese#1]
### Font 
NotoSansBalinese-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansBalinese-unhinted.zip
Date: 2018-03-04

### Font Version
Version 1.03 uh

### Issue
Below-base vowel signs overlap the descender of U+1B1B BALINESE LETTER JA JERA.

### Character data
ᬛᬸᬛᬹᬛᬺᬛᬻᬛᬼᬛᬽ
U+1B1B BALINESE LETTER JA JERA
U+1B38 BALINESE VOWEL SIGN SUKU
U+1B1B BALINESE LETTER JA JERA
U+1B39 BALINESE VOWEL SIGN SUKU ILUT
U+1B1B BALINESE LETTER JA JERA
U+1B3A BALINESE VOWEL SIGN RA REPA
U+1B1B BALINESE LETTER JA JERA
U+1B3B BALINESE VOWEL SIGN RA REPA TEDUNG
U+1B1B BALINESE LETTER JA JERA
U+1B3C BALINESE VOWEL SIGN LA LENGA
U+1B1B BALINESE LETTER JA JERA
U+1B3D BALINESE VOWEL SIGN LA LENGA TEDUNG

### Screenshot
![ᬛᬸᬛᬹᬛᬺᬛᬻᬛᬼᬛᬽ](https://user-images.githubusercontent.com/1124347/36950195-6688538a-1fc0-11e8-87aa-6e516425f8d8.png)

**Comment by simoncozens** [comment]
This is still happening in both sans and serif. In the Sans, some of the issues are mitigated by using alternate forms of the vowel signs:
![shape](https://user-images.githubusercontent.com/106728/175953376-b3d3c84a-10a6-470a-ae6d-c0594d2387e1.png)
but these alternate forms are not present in the Serif and will need drawing.

For the ja+medials I have no idea what they are actually supposed to do in that case. The longnow Bali fonts (https://github.com/longnow/bali-fonts) have the same problem. I think we need to find someone who knows what those combinations should look like.

**Comment by akufadhl** [comment]
**Ja Jera** (U+1B1B) is not really used anymore in modern orthography. and it's the rarest letter to appear in a sentence, if so, it most likely without any medials. But, if you want to handle/accomodate such combination, we can shorthen the **Ja Jera** and pair it with a short version of _nania_ (medial Ya).

Here's how it is handled in Javanese.
- Tuladha Jejeg by _R. S. Wihananto_
<img width="878" alt="Screen Shot 2022-06-29 at 01 21 36" src="https://user-images.githubusercontent.com/16867664/176244315-78f83fd0-e4f6-4e29-97ea-2c7de956160d.png">

- Noto Sans Javanese by _@adtbayuperdana_
<img width="747" alt="Screen Shot 2022-06-29 at 01 23 01" src="https://user-images.githubusercontent.com/16867664/176244533-661fca4e-52f5-4ed4-b59e-11ff3effe0d2.png">

example of **Ja Jera** usage:
- ᬫᬛᬧᬳᬶᬢ᭄ (Majhapahit)

U+1B2B BALINESE LETTER MA
U+1B1B BALINESE LETTER JA JERA
U+1B27 BALINESE LETTER PA
U+1B33 BALINESE LETTER HA
U+1B36 BALINESE VOWEL SIGN ULU
U+1B22 BALINESE LETTER TA
U+1B44 BALINESE ADEG ADEG

- ᬛᬣᬶᬢᬶᬭᬶ (Jhathitiri)

U+1B1B BALINESE LETTER JA JERA
U+1B23 BALINESE LETTER TA TAWA
U+1B36 BALINESE VOWEL SIGN ULU
U+1B22 BALINESE LETTER TA
U+1B36 BALINESE VOWEL SIGN ULU
U+1B2D BALINESE LETTER RA
U+1B36 BALINESE VOWEL SIGN ULU

- ᬛᬭᬸ (Jharu)

U+1B1B BALINESE LETTER JA JERA
U+1B2D BALINESE LETTER RA
U+1B38 BALINESE VOWEL SIGN SUKU

cc: @adtbayuperdana

**Comment by simoncozens** [comment]
I think if this is not happening in any attested words, and the Longnow fonts have the same problem, I'm going to say it's a non-problem until proved otherwise.
