### ISSUE TITLE
Noto Serif Balinese does not include third-level conjunct stack (tumpuk telu)

### ISSUE THREAD

**Issue by adtbayuperdana** [notofonts/balinese#3]
**Font** 
NotoSansBalinese Regular

**Issue**
Noto sans Balinese does not provide the glyphs necessary to write certain conjunct stack; namely the third level stack for YA, RA, RA REPA, LA, and WA. This is required to write certain words such as _munggwing_, _mantra_, etc;  all fairly common words in Balinese literature. Instead, conjuncts in Noto sans Balinese clashed together in a single space.

**Character data**

This behavior applies to semivowels ya, ra, la, and wa:

ᬬᬭᬮᬯ
U+1B2C BALINESE LETTER YA
U+1B2D BALINESE LETTER RA
U+1B2E BALINESE LETTER LA
U+1B2F BALINESE LETTER WA

Tumpuk telu also applies to two vowel signs: ra repa and ra repa tedung. They exhibit similar shape to ra, but with different input sequence.

ᬺ ᬻ
U+1B3A BALINESE VOWEL SIGN RA REPA
U+1B3B BALINESE VOWEL SIGN RA REPA TEDUNG

**Input Sequence**

1. U1B26 + U1B44 + U1B24 + U1B44 + U1B2C
2. U1B26 + U1B44 + U1B24 + U1B44 + U1B2D
3. U1B26 + U1B44 + U1B24 + U1B44 + U1B2E
4. U1B26 + U1B44 + U1B24 + U1B44 + U1B2F
5. U1B26 + U1B44 + U1B24 + U1B3A
6. U1B26 + U1B44 + U1B24 + U1B3B

in characters:
1. ᬦ​+ ᭄ + ᬤ​ + ᭄ + ᬬ
2. ᬦ​+ ᭄ + ᬤ​ + ᭄ + ᬭ  ​ 
3. ᬦ​+ ᭄ + ᬤ​ + ᭄ + ᬮ
4. ᬦ​+ ᭄ + ᬤ​ + ᭄ + ᬯ
5. ᬦ​+ ᭄ + ᬤ​ + ᬺ
6. ᬦ​+ ᭄ + ᬤ​ +  ᬻ

**Screenshot** 

![tumpuk telu noto sans bali](https://user-images.githubusercontent.com/22183655/40838122-07d953b4-65c7-11e8-8708-81e9d008df93.jpg)
\
The above image is a sequence of characters rendered in Vimala (above) and Noto sans Balinese (below). The expected behavior is shown in Vimala.

**Comment by simoncozens** [comment]
I believe I've fixed all of these apart from third-level la, which will need some drawing.
