### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by Mercury13** [notofonts/balinese#35]
### Title 
Does not build font:
fontmake: Error: In '../../../../../../tmp/tmp_59piyqf/NotoSerifBalinese-Regular.ufo': Compiling UFO failed: /tmp/tmp_59piyqf/NotoSerifBalinese-Regular.ufo/features.fea:151:1: If "languagesystem DFLT dflt" is present, it must be the first of the languagesystem statements

### Font Version
Repo head

### OS name and version
N/A

### Application name and version
N/A

**Comment by simoncozens** [comment]
Fixed!
