### ISSUE TITLE
"Unhinted" Balinese Sans TTF seems to be hinted

### ISSUE THREAD

**Issue by NorbertLindenberg** [notofonts/balinese#36]
In the current 2.004 release of Noto Sans Balinese, the hinted and unhinted TTF files have the same sizes. For the "unhinted" ones, "ttx -l" shows cvt, fpgm, and prep tables, which they probably shouldn't contain.

Obtained from
https://github.com/notofonts/balinese/releases/tag/NotoSansBalinese-v2.004

**Comment by simoncozens** [comment]
Same as #37, fixed in 429c91e
