### ISSUE TITLE
Noto Sans Balinese what is latest version? 2.003 or 2.004

### ISSUE THREAD

**Issue by Veerjee** [notofonts/balinese#37]
## Defect Report

NotoSansBalinese-Regular.ttf

> Noto fonts can be obtained from https://notofonts.github.io/
> If you find a problem with a released font, then please use this template to file a defect report.
> Before filing your report, please check if the issue has been fixed in the latest development build. You can get development builds by finding the font family on https://notofonts.github.io/ and following the link to "Development builds".

### Font 
NotoSansBalinese-Regular.ttf

### Where the font came from, and when
The version 2.003 is downloaded from the 
https://fonts.google.com/noto/specimen/Noto+Sans+Balinese
However, repo gives me https://notofonts.github.io/ version 2.004

### OS name and version
 Windows 11

### Application name and version
Word

### Issue
The version of the font downloaded from the site is 2.003 
The version of the font dowloaded from the repo is 2.004. 

The shaping results are different using Word on Windows 11. 
Windows 11: Word: Noto Sans Balinese 2.004
![image](https://github.com/notofonts/balinese/assets/120211830/0870505a-7ed1-4732-a057-f170023cc439)

Windows 11: Word: Noto Sans Balinese 2.003
![image](https://github.com/notofonts/balinese/assets/120211830/4c63a0b4-b359-44a1-8bf3-b004e77db8ec)

Copy paste following text in Word. 
"ᬩ᭄ᬬᬶᬳ" "ᬩᬵᬳ" 

### Character data
"ᬩ᭄ᬬᬶᬳ" "ᬩᬵᬳ" 

I think the issue is with the merger script. 
When I merge the v2.003 with another font. I get overlapping results as shown in the image above. 
 
If additional information is needed please do let me know here.

**Comment by simoncozens** [comment]
2.004 is the latest version; we don't always onboard to Google Fonts immediately, it can take some time. I will check that these sequences work in 2.004

**Comment by Veerjee** [comment]
[simoncozens](https://github.com/simoncozens) thank you for the fast reply. I look forward to your reply.

**Comment by simoncozens** [comment]
The sequences work correctly in 2.004; you talked about a merger script, so the problem might be with that script. I don't think there's an issue with the font.

**Comment by simoncozens** [comment]
OK, I see the problem. This is broken in the [2.004 release](https://notofonts.github.io/#balinese) but it is fixed in the [latest development builds](https://notofonts.github.io/balinese/). We need a new release, which I'll try and do soon.

**Comment by Veerjee** [comment]
This version [latest development builds](https://notofonts.github.io/balinese/). 
- still has the hinting data for the font listed under unhinted. (Reported problem not fixed)
- Version number in the name table is not increased, it should be bumped up if the problem is fixed.

**Comment by simoncozens** [comment]
Version numbers are bumped on release. I'll look into the hinting issue.

**Comment by Veerjee** [comment]
Confirm this version 
[latest development builds](https://notofonts.github.io/balinese/). 
is working as expected.

**Comment by simoncozens** [comment]
OK, found it. The source file for Noto Sans Balinese contained a "ttfautohint options" custom parameter, so fontmake thought it should autohint everything.
