### ISSUE TITLE
 The NotoSansDuployan-Regular.ttf font is incompatible for merging with any other Noto font

### ISSUE THREAD

**Issue by Veerjee** [notofonts/balinese#38]
## Defect Report

> Noto fonts can be obtained from https://notofonts.github.io/
> If you find a problem with a released font, then please use this template to file a defect report.
> Before filing your report, please check if the issue has been fixed in the latest development build. You can get development builds by finding the font family on https://notofonts.github.io/ and following the link to "Development builds".

### Title 
  > Should be brief but contain essential information.

### Font 
NotoSansDuployan-Regular.ttf

### Where the font came from, and when
From the Noto fonts repo https://notofonts.github.io/

### Font Version
Latest posted on the repo

### OS name and version
NA -- Windows 11

### Application name and version
merger script

### Issue
The merger script will not merge this font with anyother Noto font unless you remove/ignore the GPOS table.

**Comment by simoncozens** [comment]
Yes, this is true. And I'm afraid it's not something we can easily fix - the Duployan font is quite different to everything else. There is a plan to produce a more simple Duployan font, but until then you can merge with an earlier version.

**Comment by Veerjee** [comment]
How is it different? Looks like any other font. The GPOS table exists even
with the older version of the font.

**Comment by simoncozens** [comment]
There's not enough information to act on your issue. Please tell me:

* How you attempted the merge (what software, command line, etc. you used)
* What you were trying to merge it with (Is it Noto Sans Balinese? You posted this issue in the Balinese repository.)
* What error you got
* Why you believe there is a GPOS table issue
* What happened when you tried to merge with v2 of Duployan.

Any information would allow me to debug this.

**Comment by simoncozens** [comment]
Looks like pyftmerge doesn't know how to resolve overflows. Did you try installing the `uharfbuzz` Python module? This helps fontTools to pack the tables more efficiently.

**Comment by Veerjee** [comment]
How do I add uharfbuzz Python module?

**Comment by simoncozens** [comment]
pip install uharfbuzz.

(But this is no longer about a bug in a Noto font; potentially there's a bug in fontTools, but you may be able to work around it.)

**Comment by Veerjee** [comment]
I have installed the uharfbuzz Python module. However, the problem of merging the latest version of NotoSansDuployan-Regular.ttf persists.

Upon building the font with the same set of fonts as before, a merged.ttf is now generated within seconds instead of the previous versions which took 5+ minutes to generate. This is excellent work. Thank you, Simon!

Also file size is slightly smaller. File size saving are mostly coming from GPOS and some from GSUB tables.
