### ISSUE TITLE
Marks block tedung ligatures

### ISSUE THREAD

**Issue by dscorbett** [notofonts/balinese#40]
### Font
NotoSansBalinese-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/balinese/releases/tag/NotoSansBalinese-v2.005
Date: 2024-02-16

### Font version
Version 2.005

### Issue
Above- and below-base mark glyphs block tedung ligatures.

### Character data
ᬓ᬴ᬵᬓᬽ
U+1B13 BALINESE LETTER KA
U+1B34 BALINESE SIGN REREKAN
U+1B35 BALINESE VOWEL SIGN TEDUNG
U+1B13 BALINESE LETTER KA
U+1B3D BALINESE VOWEL SIGN LA LENGA TEDUNG

### Screenshot
![ᬓ᬴ᬵᬓᬽ](https://github.com/notofonts/balinese/assets/1124347/9c96aab0-7f0f-41f4-9c94-b3ea3e498f02)

**Comment by simoncozens** [comment]
This caused other problems; subscript glyphs are also marks, so ᬦ᭄ᬥᬸ now appears as

![shape](https://github.com/notofonts/balinese/assets/106728/cdec8945-1384-4448-af50-558d3e973a94)

which seems wrong. It should only be top marks which are ignored.
